[package]
name = "fusion_runtime_mem_mgr"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Framework: Memory Manager (GC & Allocator) for Fusion Runtime."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["framework", "runtime", "fusion", "memory-management", "allocator"]
categories = ["development-tools", "os::kernel-apis"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
parking_lot = { workspace = true }
libc = { workspace = true }
memmap2 = { workspace = true }
tracing = { workspace = true }
fusion_std = "1.0.0"

[dev-dependencies]
criterion = { workspace = true }


