[package]
name = "ai-gan"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Algorithm: Generative Adversarial Network components"
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["ai gan"]
categories = ["algorithms"]

[dependencies]
fusion_core = { workspace = true }
fusion_std = "1.0.0"
