cognitive-complexity-threshold = 25
enum-variant-size-threshold = 200
doc-valid-idents = [
    "Fusion",
    "FusionType",
    "Tensor",
    "Quantum",
    "QPU",
    "GPU",
    "CPU",
    "LSP",
    "JSON",
    "MIT",
    "LLVM",
]
