[package]
name = "fusion_server_grpc"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Integration: High-performance gRPC (HTTP/2) server with async/blocking support"
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["grpc", "http2", "rpc", "integration"]
categories = ["network-programming", "web-programming"]
readme = "README.md"

[features]
default = ["server", "client"]
server = []
client = []
tls = ["tonic/tls"]

[dependencies]
fusion_net = { path = "../fusion_net/", version = "0.2.0" }
fusion_std = { path = "../std" }
fusion_runtime_core = { workspace = true }
tonic = "0.10"
prost = "0.12"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
