[package]
name = "nn-3d-conv"
version = "0.1.0"
edition = "2021"
description = "3D Convolutional Layers for video and volumetric data (C * D * H * W)"
license = "MIT"

[dependencies]
fusion-core = { workspace = true }
fusion-ai-core = { workspace = true }
fusion_std = "1.0.0"


