[package]
name = "fusion_sec_penetration"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Security tool: sec-penetration. Excellent error reporting."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["tool", "cli", "fusion", "security"]
categories = ["development-tools", "command-line-utilities"]
readme = "README.md"
[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
fusion_core = { workspace = true }
fusion_std = { workspace = true }
fusion_net = { path = "../fusion_net" }
fusion_runtime_core = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }


