[package]
name = "debugger"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Debug Adapter Protocol (DAP) implementation for Fusion."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "tool", "debugger", "dap", "tool"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
fusion_core = { path = "../fusion-core", package = "fusion-core" }
anyhow = { version = "1.0.94" }
thiserror = { version = "2.0.6" }
serde = { version = "1.0.216", features = ["derive", "rc"] }
serde_json = { version = "1.0.133" }
fusion_runtime_core = { path = "../fusion_runtime_core", version = "0.2.0" }
fusion_std = { path = "../std" }

