[package]
name = "interop-python"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Integration: Language interoperability layer for python."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["integration", "fusion", "interop", "ffi"]
categories = ["external-ffi-bindings"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_std = "1.0.0"

