#ifndef hc_RISK_SCORE_H
#define hc_RISK_SCORE_H

#include <stddef.h>

/*
 * Simple quantum risk scoring API.
 * The function analyses a project's CBOM (generated by hc_generate_cbom) and
 * returns a readiness score between 0 and 100, where higher values indicate
 * better quantum‑readiness.
 */
int hc_compute_risk_score(const char *cbom_path, int *score_out);

#endif // hc_RISK_SCORE_H
