[package]
name = "fusion-chain-contract-abi"
version = "0.1.0"
edition = "2021"
authors = ["Fusion Team"]
description = "Smart contract call and event ABI"
license = "MIT"

[dependencies]
fusion_std = "1.0.0"
fusion-chain-primitives = { path = "../fusion-chain-primitives" }
