[package]
name = "fusion_llm_trie_search"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Algorithm: Fusion Algorithm crate: trie-search."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "algorithm"]
categories = ["algorithms", "science"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_llm_inference_engine = { path = "../llm-inference/", version = "0.2.0" }
fusion_std = "1.0.0"


