apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: hypercycle-vortex
  managed-by: kustomize

namespace: hypercycle

images:
  - name: hypercycle/vortex
    newTag: 2.0.2
