apiVersion: v1
kind: Service
metadata:
  name: hypercycle-vortex
  labels:
    app: hypercycle-vortex
spec:
  type: ClusterIP
  selector:
    app: hypercycle-vortex
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hypercycle-vortex-lb
  labels:
    app: hypercycle-vortex
spec:
  type: LoadBalancer
  selector:
    app: hypercycle-vortex
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
