# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fusion_core_v2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fusion_core_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66usion_core_v2.proto\x12\x0e\x66usion_core_v2\"\'\n\x12HealthCheckRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"J\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nload_index\x18\x03 \x01(\x01\"M\n\rPluginRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x13\n\x0bwasm_binary\x18\x02 \x01(\x0c\x12\x12\n\ninput_data\x18\x03 \x01(\t\"j\n\x0ePluginResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x13\n\x0boutput_data\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x01\x32\xb1\x01\n\x07Runtime\x12V\n\x0bHealthCheck\x12\".fusion_core_v2.HealthCheckRequest\x1a#.fusion_core_v2.HealthCheckResponse\x12N\n\rExecutePlugin\x12\x1d.fusion_core_v2.PluginRequest\x1a\x1e.fusion_core_v2.PluginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fusion_core_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=40
  _globals['_HEALTHCHECKREQUEST']._serialized_end=79
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=81
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=155
  _globals['_PLUGINREQUEST']._serialized_start=157
  _globals['_PLUGINREQUEST']._serialized_end=234
  _globals['_PLUGINRESPONSE']._serialized_start=236
  _globals['_PLUGINRESPONSE']._serialized_end=342
  _globals['_RUNTIME']._serialized_start=345
  _globals['_RUNTIME']._serialized_end=522
# @@protoc_insertion_point(module_scope)
