[package]
name = "faas"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Framework: Serverless Function-as-a-Service runtime and emulator."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "framework", "faas", "serverless", "framework"]
categories = ["development-tools", "framework"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_http = { path = "../http/", version = "0.2.0" }
fusion_std = { workspace = true }
fusion_runtime_core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }



