[package]
name = "version"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Fusion Tool crate: version."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "tool"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_std = { workspace = true }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true }



