[package]
name = "pqc-proxy"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Algorithm: Fusion Algorithm crate: pqc-proxy."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "algorithm"]
categories = ["algorithms", "science"]
readme = "README.md"

[dependencies]
fusion_core = { workspace = true }
fusion_runtime_core = { workspace = true }
fusion_std = { workspace = true }
fusion_net = { workspace = true }
fusion_security = { path = "../fusion-security", version = "0.2.0" }
tokio = { workspace = true, features = ["net", "io-util", "rt-multi-thread", "macros", "sync"] }
sha2 = { workspace = true }
rand = { workspace = true }

