[package]
name = "fusion-profiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Fusion profiler - Runtime performance profiling"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fusion_std = "1.0.0"
