[package]
name = "fusion-service-router"
version = "0.1.0"
edition = "2021"
authors = ["Fusion Team"]
description = "Fusion ecosystem crate: fusion-service-router"
license = "MIT"

[dependencies]
fusion_std = "1.0.0"
