[package]
name = "rest-server"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Integration: Fusion Integration crate: rest-server."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "integration"]
categories = ["network-programming", "external-ffi-bindings"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_http = { path = "../http/", version = "0.2.0" }
fusion_std = { path = "../std", version = "0.2.0" }
fusion_runtime_core = { workspace = true }
thiserror = { workspace = true }


