[package]
name = "fusion-docgen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Fusion documentation generator and search indexer"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
handlebars = { workspace = true }
fusion-core = { workspace = true }
fusion_std = "1.0.0"

