[package]
name = "fuc"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.13"
chumsky = "0.9"
ariadne = "0.3"
# Ensure LLVM 15 is installed: e.g., `sudo apt install llvm-15-dev libpolly-15-dev`
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "v18-ci", features = ["llvm18-0"] }
llvm-sys = { version = "180", features = ["prefer-dynamic"] }
thiserror = "1.0"
generational-arena = "0.2"
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0"
fusion_std = "1.0.0"
colored = "2.0"

[dev-dependencies]
# For integration tests
test-generator = "0.3"
tempfile = "3"
