[package]
name = "fusion_net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "High-performance networking leveraging fusion_runtime_core"

[dependencies]
fusion_core = { path = "../../../registry/crates/fusion_core/" }
fusion_runtime_core = { path = "../../../registry/crates/fusion_runtime_core/" }
fusion_runtime_hal = { path = "../../../registry/crates/fusion_runtime_hal/" }
socket2 = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
fusion_std = "1.0.0"

[dev-dependencies]
criterion = { workspace = true }
