[package]
name = "trusted-anchor"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Integration: Fusion Integration crate: trusted-anchor."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "integration"]
categories = ["network-programming", "external-ffi-bindings"]
readme = "README.md"
[dependencies]
fusion_core = { workspace = true }
fusion_std = "1.0.0"



