[package]
name = "fusion_sbom_generator"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Fusion Tool crate: sbom-generator."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "tool"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
fusion_core = { workspace = true }
fusion_std = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
