[package]
name = "fusion-audio"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Fusion tool: fusion-audio. Excellent error reporting."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["tool", "cli", "fusion"]
categories = ["development-tools", "command-line-utilities"]
readme = "README.md"
[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
fusion_core = { workspace = true }
fusion_std = "1.0.0"


