[package]
name = "formatter"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Tool: Fusion Tool crate: formatter."
authors = ["Fusion Team"]
repository = "https://github.com/QuantumSecureTechnologiesInc/Fusion-Programming-Language"
keywords = ["fusion", "tool"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"

[dependencies]
fusion_core = { path = "../fusion-core", package = "fusion-core" }
anyhow = { version = "1.0.94" }
thiserror = { version = "2.0.6" }
serde = { version = "1.0.216", features = ["derive", "rc"] }
toml = { version = "0.8.19" }
fusion-core = { path = "../fusion-core", package = "fusion-core" }
fusion_std = { path = "../std" }

