[package]
name = "llm-data-tokenizer"
version = "0.1.0"
edition = "2021"
description = "High-throughput, parallel data tokenization for training pipelines"
license = "MIT"

[dependencies]
fusion-core = { workspace = true }
fusion_llm_tokenizers = { path = "../llm-tokenizers", version = "0.1.0" }
tokio = { workspace = true }
fusion_std = "1.0.0"


